#! /bin/bash


# Autostart
pkill picom
pkill sxhkd
pkill batterywarn
sleep 0.1

feh --bg-fill ~/Wallpapers/nier.png

xrdb -remove &
xrdb ~/xrdb/nier/nier &
~/bin/batterywarn &
picom --config /home/tanish2002/.config/picom/picom.conf -b &

sh /home/tanish2002/.config/polybar/launch.sh &
setxkbmap -model pc105 -layout us,ru,ua -option grp:alt_shift_toggle &
systemctl --user --now start greenclip.service &
sxhkd &
# wal -R -o wal-set &
#xautolock -time 10 -locker "~/scripts/lock.sh" &
xsetroot -cursor_name left_ptr &



# Workspaces

bspc monitor -d web code media edit graphics other


# Source the colors

#source "${HOME}/.cache/wal/colors.sh"
## . "${HOME}/.cache/wal/colors.sh"


# Set the border colors

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"


# Use the line below if you are on bspwm >= 0.9.4

#bspc config presel_feedback_color "$color1"
bspc config presel_border_color "$color1"


# Borders and Gaps
bspc config border_radius        0
bspc config border_width         0
bspc config window_gap          25

# bspc config split_ratio          0.50
#bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config click_to_focus       true
bspc config pointer_motion_interval 14


# Rules
bspc rule -a firefox desktop="web"
bspc rule -a Firefox desktop="web"
bspc rule -a TelegramDesktop desktop="web" follow=off
bspc rule -a Subl3 desktop="code" follow=off
bspc rule -a mpv desktop="media" state=floating follow=on
bspc rule -a Gimp-2.10 desktop="graphics" follow=on
bspc rule -a Transmission-gtk desktop="other" state=floating follow=on
bspc rule -a discord desktop="other" state=pseudo_tiled follow=off

bspc rule -a Sxiv state=floating
bspc rule -a Xarchiver state=floating
bspc rule -a Leafpad state=floating
bspc rule -a Pcmanfm state=floating focus=on
bspc rule -a URxvt state=floating
bspc rule -a feh state=floating




# Restart dunst with the new color scheme

#mkdir -p  "${HOME}/.config/dunst"
#ln -sf    "${HOME}/.cache/wal/bspwm-dunstrc" "${HOME}/.config/dunst/bspwm-dunstrc"
#
#pkill dunst
#sleep 0.1
#dunst -conf ~/.config/dunst/bspwm-dunstrc &
bspc config bottom_padding 15
bspc config top_padding 15
sxhkd &

