#+TITLE:Doom Emacs Config
#+AUTHOR: Tanish Khare
#+STARTUP: showeverything

** Table of Contents :toc:
  - [[#fonts][FONTS]]
  - [[#doom-theme][DOOM THEME]]
  - [[#org-mode][ORG MODE]]
  - [[#language-server][Language Server]]
  - [[#line-settings][LINE SETTINGS]]
  - [[#doom-dashboard][Doom Dashboard]]
  - [[#neotree][NEOTREE]]
  - [[#tabs][Tabs]]
  - [[#elcord][Elcord]]
  - [[#disable-persistent-undo-history][Disable Persistent Undo History]]
  - [[#color-highlighting][Color Highlighting]]
  - [[#kakoune-config][Kakoune Config]]

** FONTS
Doom exposes five (optional) variables for controlling fonts in Doom. Here
are the three important ones:

+ `doom-font'
+ `doom-variable-pitch-font'
+ `doom-big-font' -- used for `doom-big-font-mode'; use this for
  presentations or streaming.

They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
font string. You generally only need these two:

#+BEGIN_SRC emacs-lisp
(setq doom-font (font-spec :family "Iosevka Term" :size 13)
      doom-big-font (font-spec :family "Iosevka Term" :size 20)
      doom-variable-pitch-font (font-spec :family "Iosevka Term" :size 13))
#+END_SRC
** DOOM THEME
#+BEGIN_SRC emacs-lisp
(setq doom-theme 'doom-solid)
#+END_SRC

** ORG MODE
#+BEGIN_SRC emacs-lisp
(setq org-directory "~/Documents/org/")
#+END_SRC

** Language Server
*** Rust
#+BEGIN_SRC emacs-lisp
(setq rustic-lsp-server 'rust-analyzer)
#+END_SRC
*** Python
@TODO
#+BEGIN_SRC emacs-lisp
#+END_SRC
*** C/C++
@TODO
#+BEGIN_SRC emacs-lisP
#+END_SRC

** LINE SETTINGS
 #+BEGIN_SRC emacs-lisp
(setq display-line-numbers-type 'relative)
#+END_SRC

** Doom Dashboard
#+BEGIN_SRC emacs-lisp
;; (setq fancy-splash-image "~/.doom.d/themes/richard.png")
(setq fancy-splash-image "/home/weeb/Downloads/rsz_uihere.png")
(setq doom-modeline-major-mode-icon t)
(add-hook '+doom-dashboard-mode-hook #'hide-mode-line-mode)
(defun doom-dashboard-widget-footer ()
  (insert
   "\n"
   (+doom-dashboard--center
    (- +doom-dashboard--width 2)
    "Config by Tanish2002")
   "\n"
   (+doom-dashboard--center
    (- +doom-dashboard--width 5)
    (with-temp-buffer
      (insert-text-button (or (all-the-icons-faicon "heart" :face 'error :height 1.5 :v-adjust -0.5)
                              (propertize "E M A C S" 'face 'font-lock-keyword-face))
                          'action (lambda (_) (browse-url "https://github.com/karetsu"))
                          'follow-link t
                          'help-echo "github")
      (buffer-string)))
   "\n"))
;; (custom-set-faces!
;;   '(doom-dashboard-footer-icon :inherit all-the-icons-red))
#+END_SRC
** NEOTREE
Setting the neotree width to be adjustable.
#+BEGIN_SRC emacs-lisp
(use-package! neotree
  :config
  (setq neo-window-fixed-size nil
        doom-themes-neotree-file-icons t))
#+END_SRC

** Tabs
Tabs like vscode
#+BEGIN_SRC emacs-lisp
(use-package! centaur-tabs
   :config
   (centaur-tabs-group-by-projectile-project)
   (centaur-tabs-mode t)
   (setq centaur-tabs-style "bar"
         centaur-tabs-height 32
         centaur-tabs-set-icons t
         centaur-tabs-set-modified-marker t
         centaur-tabs-set-bar 'under
         x-underline-at-descent-line t)
   :bind
   ("C-<left>" . centaur-tabs-backward)
   ("C-<right>" . centaur-tabs-forward))
#+END_SRC
** Elcord
Discord Rich Presenece Integration
#+BEGIN_SRC emacs-lisp
(use-package! elcord
  :config
  (elcord-mode))
#+END_SRC

** Disable Persistent Undo History
#+BEGIN_SRC emacs-lisp
(remove-hook 'undo-fu-mode-hook #'global-undo-fu-session-mode)
#+END_SRC

** Color Highlighting
#+BEGIN_SRC emacs-lisp
(defun xah-syntax-color-hex ()
  "Syntax color text of the form 「#ff1100」 and 「#abc」 in current buffer.
URL `http://ergoemacs.org/emacs/emacs_CSS_colors.html'
Version 2017-03-12"
  (interactive)
  (font-lock-add-keywords
   nil
   '(("#[[:xdigit:]]\\{3\\}"
      (0 (put-text-property
          (match-beginning 0)
          (match-end 0)
          'face (list :background
                      (let* (
                             (ms (match-string-no-properties 0))
                             (r (substring ms 1 2))
                             (g (substring ms 2 3))
                             (b (substring ms 3 4)))
                        (concat "#" r r g g b b))))))
     ("#[[:xdigit:]]\\{6\\}"
      (0 (put-text-property
          (match-beginning 0)
          (match-end 0)
          'face (list :background (match-string-no-properties 0)))))))
  (font-lock-flush))
#+END_SRC
** Kakoune Config
#+BEGIN_SRC emacs-lisp
;; (setq evil-default-state 'emacs)

(load! "kak.el")
;; (use-package! boon
;;    :config
;;    (require 'boon-qwerty)
;;    (boon-mode))
#+END_SRC
